server:
  port: 1024
spring:
  datasource:
    url: jdbc:h2:file:D:\Max\repos\RestBookShelf;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json